-- Up Migration
-- Every other table uses ULID (TEXT) primary keys generated by the
-- application. task_history is different: its rows are inserted
-- exclusively by the audit triggers below, never by application code,
-- so there is no client-side ID to provide. UUID + gen_random_uuid()
-- lets Postgres generate the key in-trigger without an extension.

CREATE TABLE task_history (
  history_id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  task_id TEXT NOT NULL,
  change_type VARCHAR(10) NOT NULL,
  entity VARCHAR(10) NOT NULL,
  field VARCHAR(50),
  old_value TEXT,
  new_value TEXT,
  changed_at TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT task_history_task_id_fk FOREIGN KEY (task_id)
  REFERENCES tasks (task_id)
  ON DELETE CASCADE
);


-- Down Migration

DROP TABLE task_history;
